name: kheti
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_dialogflow: ^0.1.3  #integrating dialogueflow chatbot.
  url_launcher: ^5.7.10       #launching the external url.
  http: ^0.12.2               #getting http requests.
  geolocator: ^6.1.8          #locating user latitude and logitude.
  geocoder: ^0.2.1            #converting latitude and longitude into address.
  html: ^0.14.0+4             #opening websites and webpages
  flutter_staggered_animations: ^0.1.2  #animating the results
  flutter_text_to_speech: ^3.0.7    #reading the written texts.
  tflite: ^1.1.1              #integrating mobilenet-ssd and yolo-v2.
  image_picker: ^0.6.7+14     #picking image from the gallery.
  flutter_facebook_login: ^3.0.0 #logging with facebook
  firebase_auth: ^0.18.4+1    #authencating firebase.
  firebase_core: ^0.5.3       #accessing the firebase.
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"  #changing the app icon.
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"  #app icon

flutter:
  assets:
    - assets/service.json
    - assets/images/
    - assets/tflite/
  
  uses-material-design: true

  
